# Linear queue for the main branch.
queue_rules:
  - name: main
    commit_message_template: |-
      {{ title }} (#{{ number }})

      {{ body | trim }}
    queue_conditions:
      - base=main
      - or:
          - check-pending=integration-test-result
          - check-success=integration-test-result
          - label=bypass:integration
    merge_conditions:
      - base=main
      # Require integration tests before merging only
      - or:
          - label=bypass:integration
          - check-success=integration-test-result

pull_request_rules:
  - name: merge to main
    conditions:
      - base=main
      - label=automerge:no-update
      - or:
          - '#commits-behind=0'
          - label=bypass:linear-history
    actions:
      queue:
        name: main
        merge_method: merge
  - name: rebase updates then merge to main
    conditions:
      - base=main
      - label=automerge:rebase
    actions:
      queue:
        name: main
        merge_method: merge
        update_method: rebase
  - name: squash to main
    conditions:
      - base=main
      - label=automerge:squash
    actions:
      queue:
        name: main
        merge_method: squash
