name: Protobuf
# Protobuf runs protobuf related CI checksss:
# - buf (https://buf.build/) lint
# - buf check-breakage
# - check protobuf definitions are up-to-date
on:
  pull_request:
  merge_group:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  breakage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
      - name: check-breakage
        run: |
          status=0
          if [ $status -eq 0 ]; then
            if [ "$EXPECT_BREAKAGE" = "true" ]; then
              echo "Expected breakage, but got no breakage."
              exit 1
            fi
            echo "As expected, no breakage was detected."
          elif [ "$EXPECT_BREAKAGE" == "true" ]; then
            echo "Expected breakage, and got it."
            exit 0
          else
            echo "Unexpected breakage detected."
          fi
          exit $status
        env:
          REPO: https://github.com/${{ github.repository }}.git
          BRANCH: ${{ github.base_ref}}
          EXPECT_BREAKAGE: ${{ contains( github.event.pull_request.labels.*.name, 'proto:expect-breakage') }}

  post-proto:
    uses: ./.github/workflows/result.yml
    if: (success() || failure())
    secrets:
      SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
    with:
      dry-run: ${{ github.event_name == 'pull_request' }}
      needs-json: ${{ toJson(needs) }}
    needs:
      - breakage